micronaut:
  application:
    name: helloWorld
  executors:
      io:
        type: fixed
        nThreads: 75
  router:
    versioning:
      enabled: true
      default-version: 3
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
netty:
  default:
    allocator:
      max-order: 3
datasource:
  url: mysql://192.168.0.1:3306/abc
my:
  engine:
    cylinders: 668
    manufacturer: "time to go!!"
    color: RED
  host: www.yumi.com
  port: 80
  jpa:
    default:
      hibernate:
        hbm2ddl:
          auto: update
      show_sql: true